### ISSUE TITLE
Crash on spdx identifier is wrong

### ISSUE THREAD

**Issue by kentakang** [investycorp/oss-license-check#13]
# Bug Report
## Summary
oss-license-check is crashed on spdx identifier is wrong.
Like below,
```
var getLicenseFullName = function (spdxIdentifier) { return full_1.default[spdxIdentifier].name; };
                                                                                           ^

TypeError: Cannot read property 'name' of undefined
    at Object.getLicenseFullName (/Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/licenses/index.js:10:92)
    at /Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/output/resultToHTML.js:12:434
    at Array.map (<anonymous>)
    at Object.resultToHTML [as default] (/Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/output/resultToHTML.js:12:31)
    at /Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/program.js:81:49
    at step (/Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/program.js:34:23)
    at Object.next (/Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/program.js:15:53)
    at fulfilled (/Users/kentakang/Desktop/Projects/project/node_modules/oss-license-check/dist/program.js:6:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by kentakang** [comment]
fix on #15
